name: Deploying Container on ECS

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build Application
    runs-on: docker:latest
    script:
      - docker build -t tejasacharekar/nginxalpine:3 .

