name: Deploying Container on ECS

on:
  push:
    branches: [ "main" ]

stages:
 - build

build:
  stage: build
  steps:
    - image: docker:latest
      script: 
      - docker build -t tejasacharekar/nginxalpine:3 .



