name: Deploying Container on ECS

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tejasacharekar/nginxalpine:latest && docker images
  
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Pushing Image to Docker Registry
      run: docker push tejasacharekar/nginxalpine:latest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
    
    - name: Fill in the new image ID in the Amazon ECS task definition
      run: |
        aws ecs describe-task-definition --task-definition onlineassesmentdeploy > onlineassesmentdeploy.json
        sed -i 's/tejasacharekar\/nginxalpine/tejasacharekar\/nginxalpine:2/g' onlineassesmentdeploy.json
        ls -all && pwd
        aws register-task-definition --cli-input-json file://onlineassesmentdeploy.json
        ## aws ecs update-service --cluster onlineAssessment --service onlineAssessment --task-definition onlineassesmentdeploy
