name: Deploying Container on ECS

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    steps:
      - uses: actions/checkout@v1
      - name: Build Application
          runs-on: docker:latest
          run: docker build -t tejasacharekar/nginxalpine:3 .


